[package]
name = "hachiya"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
camino = "1.2.2"
cargo_metadata = "0.23.1"
dylib = "0.0.3"
glob = "0.3.3"
serde = "1.0.228"
toml = "0.9.11"
